on:
  push:
    branches:
      - main
      - develop
jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      runtime_group: ${{ steps.set-env.outputs.runtime_group }}
    steps:
      - id: set-env
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "::set-output name=environment::production"
            echo "::set-output name=runtime_group::default"
          else
            echo "::set-output name=environment::staging"
            echo "::set-output name=runtime_group::staging"
          fi
  deploy-staging:
    runs-on: ubuntu-latest
    needs: "set-env"
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.12.0
      - name: Run deck sync
        run: |
          deck sync \
            --konnect-email ${{ secrets.KONNECT_EMAIL }} \
            --konnect-password ${{ secrets.KONNECT_PASSWORD }} \
            --konnect-runtime-group-name ${{ needs.set-env.outputs.runtime_group }}
