on:
  push:
    branches:
      - main
      - develop
jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: echo "::set-output name=environment::staging"
  deploy-staging:
    runs-on: ubuntu-latest
    needs: "set-env"
    environment: ${{ needs.set-env.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.12.0
      - name: Run deck sync
        run: |
          deck sync \
            --konnect-email ${{ secrets.KONNECT_EMAIL }} \
            --konnect-password ${{ secrets.KONNECT_PASSWORD }} \
            --konnect-runtime-group-name staging
