on:
  push:
    branches:
      - main
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.12.0
      - run: deck version
