on:
  push:
    branches:
      - main
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.12.0
      - name: Run deck sync
        run: |
          deck sync \
            --konnect-email ${{ secrets.KONNECT_EMAIL }} \
            --konnect-password ${{ secrets.KONNECT_PASSWORD }} \
            --konnect-runtime-group-name staging
